Add gitlab connector and update discord connector
second-state/reactor-connector-rs pull request #7
Opened 2022-08-02 10:14 UTC by chen982

2022-08-02 10:57 UTC, ho-229 requested changes

2022-08-02 10:57 UTC, ho-229 commented on discord/src/main.rs
> +fn new_http_client() -> Client {
reqwest::Client can be reused, it should be static, you can also see our latest code.

2022-08-02 11:00 UTC, ho-229 requested changes

2022-08-02 11:00 UTC, ho-229 commented on discord/src/main.rs
> +fn encrypt(data: &str) -> String {
We found that using `Rsa` makes encryption easier and we hope to use it in the latest code. You can refer to https://github.com/second-state/reactor-connector-rs/blob/62fef756065827f6de7edfcfc3b093635ba42f70/github/src/main.rs#L118

2022-08-04 12:12 UTC, chen982 commented
The above two changes have been resolved

2022-08-04 12:59 UTC, ho-229 approved these changes

2022-08-04 13:00 UTC, merged